

uint8 tyre_index         #轮编号
uint8 tyre_temperature   #该轮胎温度 ℃
float64 type_pressure   #该轮胎气压  kpa
uint8 tyre_leakage         #漏气   0x00:正常   0x01:告警
uint8 tyre_highpressure     #高压  0x00:正常   0x01:告警
uint8 tyre_lowpressure      #低压  0x00:正常   0x01:告警
uint8 tyre_hightemperature  #高温  0x00:正常   0x01:告警
uint8 tyre_battery_low #电池电压低  0x00:正常   0x01:告警
uint8 tyre_no_signal  #信号异常     0x00:正常   0x01:告警


